### ISSUE TITLE
Create Database Tables

### ISSUE THREAD

**Issue by victorlora** [BarTabs/bartabs#52]
- user
-     objectid
-     first_name
-     last_name
-     middle_initial
-     phone_number
-     password
-     type
-     created_timestamp
-     modified_timestamp
- menu
-     objectid
-     bar_id
-     title
-     type
-     created_timestamp
-     modified_timestamp
- menu_items
-     objectid
-     menu_id
-     name
-     description
-     price
-     available
-     inventory_id
-     created_timestamp
-     modified_timestamp
- bars
-     objectid
-     name
-     location_id
-     owner_id
-     created_timestamp
-     modified_timestamp
- review
-     objectid
-     bar_id
-     reviewer_id
-     message
-     rating
-     created_timestamp
-     modified_timestamp
- location
-     objectid
-     address1
-     address2
-     city
-     zip_code
-     geo_area_id
- geo_area
- employee
-     objectid
-     user_id
-     bar_id
- mixology_ingredient
-     objectid
-     menu_item_id
-     inventory_id
-     qty
-     qty_type
-     comment
- inventory
- purchase_history
- orders
-     objectid
-     menu_item_id
-     order_timestamp
-     user_id
- 
-

**Comment by rongerschel** [comment]
User:
CREATE TABLE user (objectid serial, first_name varchar(20) NOT NULL, last_name varchar(20) NOT NULL, middle_initial varchar(1), phone_number varchar(15), username varchar(20) NOT NULL, password varchar(64) NOT NULL, user_type bigint, created_timestamp timestamp NOT NULL DEFAULT now(), modified_timestamp timestamp DEFAULT now());

Menu:
CREATE TABLE menu (objectid serial, barid varchar(10) NOT NULL, title varchar(30) NOT NULL, type varchar(10), created_timestamp timestamp NOT NULL DEFAULT now(), modified_timestamp timestamp DEFAULT now());

Menu_Items:
CREATE TABLE menu_items (objectid serial, menu_id varchar(10) NOT NULL, name varchar(30) NOT NULL, description varchar(50), price decimal(6,2), available varchar(1), inventory_id varchar(10), created_timestamp timestamp NOT NULL DEFAULT now(), modified_timestamp timestamp DEFAULT now());

Bars:
CREATE TABLE bars (objectid serial, name varchar(20) NOT NULL, location_id varchar(10) NOT NULL, owner_id varchar(10) NOT NULL, created_timestamp timestamp NOT NULL DEFAULT now(), modified_timestamp timestamp DEFAULT now());

Review:
CREATE TABLE review (objectid serial, bar_id varchar(20) NOT NULL, reviewer_id varchar(10) NOT NULL, message varchar(100), rating varchar(5), created_timestamp timestamp NOT NULL DEFAULT now(), modified_timestamp timestamp DEFAULT now());

Location:
CREATE TABLE location (objectid serial, address1 varchar(25) NOT NULL, address2 varchar(25), city varchar(20) NOT NULL, zip_code varchar(8) NOT NULL, geo_area_id varchar(20));

Employee:
CREATE TABLE employee (objectid serial, user_id varchar(25) NOT NULL, password varchar(64) NOT NULL, bar_id varchar(10) NOT NULL);

Mixology_Ingredient:
CREATE TABLE mixology_ingredient (objectid serial, menu_item_id varchar(10) NOT NULL, inventory_id varchar(10) NOT NULL, quantity varchar(10), quantity_type varchar(15), comment varchar(60));

Orders:
CREATE TABLE orders (objectid serial, menu_item_id varchar(10) NOT NULL, order_timestamp timestamp DEFAULT now(), user_id varchar(10) NOT NULL);
